name: Copy WebGL build to web branch

on:
  push:
    branches:
      - main

jobs:
  copy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "IceWaterNotIce"
          git config --global user.email "icewaternotice@gmail.com"

      - name: Copy WebGL build to web branch
        run: |
          git fetch
          git checkout web
          # Delete all existing files in web
          rm -rf *
          # Copy new files from main
          git checkout main -- Builds/Web/*
          mv Builds/Web/* . 
          git add -A
          git commit -m "Update WebGL build from main"
          git push origin web